# Generated by Django 5.0.3 on 2024-03-09 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='callboard.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='contacts',
            field=models.TextField(verbose_name='Contacts'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='content',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Show in list'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='price',
            field=models.FloatField(default=0, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
    ]
